/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedStakeUserStakeListIndexRouteImport } from './routes/_authenticated/stake/user-stake-list/index'
import { Route as AuthenticatedStakeContractIndexRouteImport } from './routes/_authenticated/stake/contract/index'
import { Route as AuthenticatedStakeAssetIndexRouteImport } from './routes/_authenticated/stake/asset/index'
import { Route as AuthenticatedCryptoWithdrawalIndexRouteImport } from './routes/_authenticated/crypto/withdrawal/index'
import { Route as AuthenticatedCryptoWalletAddressIndexRouteImport } from './routes/_authenticated/crypto/wallet-address/index'
import { Route as AuthenticatedCryptoDepositIndexRouteImport } from './routes/_authenticated/crypto/deposit/index'
import { Route as AuthenticatedCryptoCoinsIndexRouteImport } from './routes/_authenticated/crypto/coins/index'
import { Route as AuthenticatedBankWithdrawalIndexRouteImport } from './routes/_authenticated/bank/withdrawal/index'
import { Route as AuthenticatedBankWalletsIndexRouteImport } from './routes/_authenticated/bank/wallets/index'
import { Route as AuthenticatedBankExchangeTxnIndexRouteImport } from './routes/_authenticated/bank/exchange-txn/index'
import { Route as AuthenticatedBankDepositIndexRouteImport } from './routes/_authenticated/bank/deposit/index'
import { Route as AuthenticatedAdditionalNewsIndexRouteImport } from './routes/_authenticated/additional/news/index'
import { Route as AuthenticateduserManagementUserInformationIndexRouteImport } from './routes/_authenticated/(user-management)/user-information/index'
import { Route as AuthenticateduserManagementUserInformationIdRouteImport } from './routes/_authenticated/(user-management)/user-information/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStakeUserStakeListIndexRoute =
  AuthenticatedStakeUserStakeListIndexRouteImport.update({
    id: '/stake/user-stake-list/',
    path: '/stake/user-stake-list/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStakeContractIndexRoute =
  AuthenticatedStakeContractIndexRouteImport.update({
    id: '/stake/contract/',
    path: '/stake/contract/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStakeAssetIndexRoute =
  AuthenticatedStakeAssetIndexRouteImport.update({
    id: '/stake/asset/',
    path: '/stake/asset/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCryptoWithdrawalIndexRoute =
  AuthenticatedCryptoWithdrawalIndexRouteImport.update({
    id: '/crypto/withdrawal/',
    path: '/crypto/withdrawal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCryptoWalletAddressIndexRoute =
  AuthenticatedCryptoWalletAddressIndexRouteImport.update({
    id: '/crypto/wallet-address/',
    path: '/crypto/wallet-address/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCryptoDepositIndexRoute =
  AuthenticatedCryptoDepositIndexRouteImport.update({
    id: '/crypto/deposit/',
    path: '/crypto/deposit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCryptoCoinsIndexRoute =
  AuthenticatedCryptoCoinsIndexRouteImport.update({
    id: '/crypto/coins/',
    path: '/crypto/coins/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBankWithdrawalIndexRoute =
  AuthenticatedBankWithdrawalIndexRouteImport.update({
    id: '/bank/withdrawal/',
    path: '/bank/withdrawal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBankWalletsIndexRoute =
  AuthenticatedBankWalletsIndexRouteImport.update({
    id: '/bank/wallets/',
    path: '/bank/wallets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBankExchangeTxnIndexRoute =
  AuthenticatedBankExchangeTxnIndexRouteImport.update({
    id: '/bank/exchange-txn/',
    path: '/bank/exchange-txn/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBankDepositIndexRoute =
  AuthenticatedBankDepositIndexRouteImport.update({
    id: '/bank/deposit/',
    path: '/bank/deposit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdditionalNewsIndexRoute =
  AuthenticatedAdditionalNewsIndexRouteImport.update({
    id: '/additional/news/',
    path: '/additional/news/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticateduserManagementUserInformationIndexRoute =
  AuthenticateduserManagementUserInformationIndexRouteImport.update({
    id: '/(user-management)/user-information/',
    path: '/user-information/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticateduserManagementUserInformationIdRoute =
  AuthenticateduserManagementUserInformationIdRouteImport.update({
    id: '/(user-management)/user-information/$id',
    path: '/user-information/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/user-information/$id': typeof AuthenticateduserManagementUserInformationIdRoute
  '/user-information': typeof AuthenticateduserManagementUserInformationIndexRoute
  '/additional/news': typeof AuthenticatedAdditionalNewsIndexRoute
  '/bank/deposit': typeof AuthenticatedBankDepositIndexRoute
  '/bank/exchange-txn': typeof AuthenticatedBankExchangeTxnIndexRoute
  '/bank/wallets': typeof AuthenticatedBankWalletsIndexRoute
  '/bank/withdrawal': typeof AuthenticatedBankWithdrawalIndexRoute
  '/crypto/coins': typeof AuthenticatedCryptoCoinsIndexRoute
  '/crypto/deposit': typeof AuthenticatedCryptoDepositIndexRoute
  '/crypto/wallet-address': typeof AuthenticatedCryptoWalletAddressIndexRoute
  '/crypto/withdrawal': typeof AuthenticatedCryptoWithdrawalIndexRoute
  '/stake/asset': typeof AuthenticatedStakeAssetIndexRoute
  '/stake/contract': typeof AuthenticatedStakeContractIndexRoute
  '/stake/user-stake-list': typeof AuthenticatedStakeUserStakeListIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/user-information/$id': typeof AuthenticateduserManagementUserInformationIdRoute
  '/user-information': typeof AuthenticateduserManagementUserInformationIndexRoute
  '/additional/news': typeof AuthenticatedAdditionalNewsIndexRoute
  '/bank/deposit': typeof AuthenticatedBankDepositIndexRoute
  '/bank/exchange-txn': typeof AuthenticatedBankExchangeTxnIndexRoute
  '/bank/wallets': typeof AuthenticatedBankWalletsIndexRoute
  '/bank/withdrawal': typeof AuthenticatedBankWithdrawalIndexRoute
  '/crypto/coins': typeof AuthenticatedCryptoCoinsIndexRoute
  '/crypto/deposit': typeof AuthenticatedCryptoDepositIndexRoute
  '/crypto/wallet-address': typeof AuthenticatedCryptoWalletAddressIndexRoute
  '/crypto/withdrawal': typeof AuthenticatedCryptoWithdrawalIndexRoute
  '/stake/asset': typeof AuthenticatedStakeAssetIndexRoute
  '/stake/contract': typeof AuthenticatedStakeContractIndexRoute
  '/stake/user-stake-list': typeof AuthenticatedStakeUserStakeListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/(user-management)/user-information/$id': typeof AuthenticateduserManagementUserInformationIdRoute
  '/_authenticated/(user-management)/user-information/': typeof AuthenticateduserManagementUserInformationIndexRoute
  '/_authenticated/additional/news/': typeof AuthenticatedAdditionalNewsIndexRoute
  '/_authenticated/bank/deposit/': typeof AuthenticatedBankDepositIndexRoute
  '/_authenticated/bank/exchange-txn/': typeof AuthenticatedBankExchangeTxnIndexRoute
  '/_authenticated/bank/wallets/': typeof AuthenticatedBankWalletsIndexRoute
  '/_authenticated/bank/withdrawal/': typeof AuthenticatedBankWithdrawalIndexRoute
  '/_authenticated/crypto/coins/': typeof AuthenticatedCryptoCoinsIndexRoute
  '/_authenticated/crypto/deposit/': typeof AuthenticatedCryptoDepositIndexRoute
  '/_authenticated/crypto/wallet-address/': typeof AuthenticatedCryptoWalletAddressIndexRoute
  '/_authenticated/crypto/withdrawal/': typeof AuthenticatedCryptoWithdrawalIndexRoute
  '/_authenticated/stake/asset/': typeof AuthenticatedStakeAssetIndexRoute
  '/_authenticated/stake/contract/': typeof AuthenticatedStakeContractIndexRoute
  '/_authenticated/stake/user-stake-list/': typeof AuthenticatedStakeUserStakeListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/user-information/$id'
    | '/user-information'
    | '/additional/news'
    | '/bank/deposit'
    | '/bank/exchange-txn'
    | '/bank/wallets'
    | '/bank/withdrawal'
    | '/crypto/coins'
    | '/crypto/deposit'
    | '/crypto/wallet-address'
    | '/crypto/withdrawal'
    | '/stake/asset'
    | '/stake/contract'
    | '/stake/user-stake-list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/user-information/$id'
    | '/user-information'
    | '/additional/news'
    | '/bank/deposit'
    | '/bank/exchange-txn'
    | '/bank/wallets'
    | '/bank/withdrawal'
    | '/crypto/coins'
    | '/crypto/deposit'
    | '/crypto/wallet-address'
    | '/crypto/withdrawal'
    | '/stake/asset'
    | '/stake/contract'
    | '/stake/user-stake-list'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/(user-management)/user-information/$id'
    | '/_authenticated/(user-management)/user-information/'
    | '/_authenticated/additional/news/'
    | '/_authenticated/bank/deposit/'
    | '/_authenticated/bank/exchange-txn/'
    | '/_authenticated/bank/wallets/'
    | '/_authenticated/bank/withdrawal/'
    | '/_authenticated/crypto/coins/'
    | '/_authenticated/crypto/deposit/'
    | '/_authenticated/crypto/wallet-address/'
    | '/_authenticated/crypto/withdrawal/'
    | '/_authenticated/stake/asset/'
    | '/_authenticated/stake/contract/'
    | '/_authenticated/stake/user-stake-list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stake/user-stake-list/': {
      id: '/_authenticated/stake/user-stake-list/'
      path: '/stake/user-stake-list'
      fullPath: '/stake/user-stake-list'
      preLoaderRoute: typeof AuthenticatedStakeUserStakeListIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stake/contract/': {
      id: '/_authenticated/stake/contract/'
      path: '/stake/contract'
      fullPath: '/stake/contract'
      preLoaderRoute: typeof AuthenticatedStakeContractIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stake/asset/': {
      id: '/_authenticated/stake/asset/'
      path: '/stake/asset'
      fullPath: '/stake/asset'
      preLoaderRoute: typeof AuthenticatedStakeAssetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crypto/withdrawal/': {
      id: '/_authenticated/crypto/withdrawal/'
      path: '/crypto/withdrawal'
      fullPath: '/crypto/withdrawal'
      preLoaderRoute: typeof AuthenticatedCryptoWithdrawalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crypto/wallet-address/': {
      id: '/_authenticated/crypto/wallet-address/'
      path: '/crypto/wallet-address'
      fullPath: '/crypto/wallet-address'
      preLoaderRoute: typeof AuthenticatedCryptoWalletAddressIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crypto/deposit/': {
      id: '/_authenticated/crypto/deposit/'
      path: '/crypto/deposit'
      fullPath: '/crypto/deposit'
      preLoaderRoute: typeof AuthenticatedCryptoDepositIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crypto/coins/': {
      id: '/_authenticated/crypto/coins/'
      path: '/crypto/coins'
      fullPath: '/crypto/coins'
      preLoaderRoute: typeof AuthenticatedCryptoCoinsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank/withdrawal/': {
      id: '/_authenticated/bank/withdrawal/'
      path: '/bank/withdrawal'
      fullPath: '/bank/withdrawal'
      preLoaderRoute: typeof AuthenticatedBankWithdrawalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank/wallets/': {
      id: '/_authenticated/bank/wallets/'
      path: '/bank/wallets'
      fullPath: '/bank/wallets'
      preLoaderRoute: typeof AuthenticatedBankWalletsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank/exchange-txn/': {
      id: '/_authenticated/bank/exchange-txn/'
      path: '/bank/exchange-txn'
      fullPath: '/bank/exchange-txn'
      preLoaderRoute: typeof AuthenticatedBankExchangeTxnIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank/deposit/': {
      id: '/_authenticated/bank/deposit/'
      path: '/bank/deposit'
      fullPath: '/bank/deposit'
      preLoaderRoute: typeof AuthenticatedBankDepositIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/additional/news/': {
      id: '/_authenticated/additional/news/'
      path: '/additional/news'
      fullPath: '/additional/news'
      preLoaderRoute: typeof AuthenticatedAdditionalNewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(user-management)/user-information/': {
      id: '/_authenticated/(user-management)/user-information/'
      path: '/user-information'
      fullPath: '/user-information'
      preLoaderRoute: typeof AuthenticateduserManagementUserInformationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(user-management)/user-information/$id': {
      id: '/_authenticated/(user-management)/user-information/$id'
      path: '/user-information/$id'
      fullPath: '/user-information/$id'
      preLoaderRoute: typeof AuthenticateduserManagementUserInformationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticateduserManagementUserInformationIdRoute: typeof AuthenticateduserManagementUserInformationIdRoute
  AuthenticateduserManagementUserInformationIndexRoute: typeof AuthenticateduserManagementUserInformationIndexRoute
  AuthenticatedAdditionalNewsIndexRoute: typeof AuthenticatedAdditionalNewsIndexRoute
  AuthenticatedBankDepositIndexRoute: typeof AuthenticatedBankDepositIndexRoute
  AuthenticatedBankExchangeTxnIndexRoute: typeof AuthenticatedBankExchangeTxnIndexRoute
  AuthenticatedBankWalletsIndexRoute: typeof AuthenticatedBankWalletsIndexRoute
  AuthenticatedBankWithdrawalIndexRoute: typeof AuthenticatedBankWithdrawalIndexRoute
  AuthenticatedCryptoCoinsIndexRoute: typeof AuthenticatedCryptoCoinsIndexRoute
  AuthenticatedCryptoDepositIndexRoute: typeof AuthenticatedCryptoDepositIndexRoute
  AuthenticatedCryptoWalletAddressIndexRoute: typeof AuthenticatedCryptoWalletAddressIndexRoute
  AuthenticatedCryptoWithdrawalIndexRoute: typeof AuthenticatedCryptoWithdrawalIndexRoute
  AuthenticatedStakeAssetIndexRoute: typeof AuthenticatedStakeAssetIndexRoute
  AuthenticatedStakeContractIndexRoute: typeof AuthenticatedStakeContractIndexRoute
  AuthenticatedStakeUserStakeListIndexRoute: typeof AuthenticatedStakeUserStakeListIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticateduserManagementUserInformationIdRoute:
    AuthenticateduserManagementUserInformationIdRoute,
  AuthenticateduserManagementUserInformationIndexRoute:
    AuthenticateduserManagementUserInformationIndexRoute,
  AuthenticatedAdditionalNewsIndexRoute: AuthenticatedAdditionalNewsIndexRoute,
  AuthenticatedBankDepositIndexRoute: AuthenticatedBankDepositIndexRoute,
  AuthenticatedBankExchangeTxnIndexRoute:
    AuthenticatedBankExchangeTxnIndexRoute,
  AuthenticatedBankWalletsIndexRoute: AuthenticatedBankWalletsIndexRoute,
  AuthenticatedBankWithdrawalIndexRoute: AuthenticatedBankWithdrawalIndexRoute,
  AuthenticatedCryptoCoinsIndexRoute: AuthenticatedCryptoCoinsIndexRoute,
  AuthenticatedCryptoDepositIndexRoute: AuthenticatedCryptoDepositIndexRoute,
  AuthenticatedCryptoWalletAddressIndexRoute:
    AuthenticatedCryptoWalletAddressIndexRoute,
  AuthenticatedCryptoWithdrawalIndexRoute:
    AuthenticatedCryptoWithdrawalIndexRoute,
  AuthenticatedStakeAssetIndexRoute: AuthenticatedStakeAssetIndexRoute,
  AuthenticatedStakeContractIndexRoute: AuthenticatedStakeContractIndexRoute,
  AuthenticatedStakeUserStakeListIndexRoute:
    AuthenticatedStakeUserStakeListIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
